services:
  telegram-api-server:
    image: aiogram/telegram-bot-api:latest
    restart: unless-stopped
    environment:
      TELEGRAM_API_ID: ${TELEGRAM_API_ID}
      TELEGRAM_API_HASH: ${TELEGRAM_API_HASH}
      TELEGRAM_STAT: "1"
    volumes:
      - ./downloads:/var/lib/telegram-bot-api
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # максимальный размер одного файла лога
        max-file: "9"     # хранить 9 файлов × 10 МБ = 90 МБ
    networks:
      - botnet

  bot:
    build:
      context: .
      dockerfile: Dockerfile.python
    restart: unless-stopped
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_API_URL=http://telegram-api-server:8081
      - MAX_FILE_SIZE_MB=2000
    env_file:
      - .env
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt
    networks:
      - botnet
    depends_on:
      - telegram-api-server

networks:
  botnet:
    driver: bridge
